#!/usr/bin/env python3
import os
import sys
import nltk

from helpers import get_user_timeline
from analyzer import Analyzer
from termcolor import colored

if len(sys.argv) != 2:
    print("Usage: ./tweets <twitter_name>")
    exit(1)

# absolute paths to lists
positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")

# instantiate analyzer
analyzer = Analyzer(positives, negatives)

tweet = get_user_timeline(sys.argv[1], 10)
if tweet is None:
    print("Cannot access timeline. Profile is private or doesn't exist.")
    exit(1)

tokenizer = nltk.tokenize.TweetTokenizer()

for i in tweet:
    score = 0
    for j in tokenizer.tokenize(i):
        score += analyzer.analyze(j)
    if score > 0:
        print(colored(i, "green"))
    elif score < 0:
        print(colored(i, "red"))
    else:
        print(colored(i, "yellow"))